- name: create user home
  file: path={{nfsdir}}/{{user}} state=directory mode=0755 owner={{user}} group={{group}}

- name: create user ssh folder
  file: path={{nfsdir}}/{{user}}/.ssh state=directory mode=0700 owner={{user}} group={{group}}

- copy: src={{ item }} dest={{nfsdir}}/{{user}}/.ssh/ owner={{user}} group={{group}} mode=0600
  with_fileglob: 
    - id_rsa*

- copy:
    src: id_rsa.pub
    dest: "{{nfsdir}}/{{user}}/.ssh/authorized_keys"
    owner: "{{user}}"
    group: "{{group}}"
    mode: 0600

- copy:
    src: config
    dest: "{{nfsdir}}/{{user}}/.ssh/config"
    owner: "{{user}}"
    group: "{{group}}"
    mode: 0644
