- name: create test user group
  group: name=testusers gid=1010

- name: create test user
  user: name=testuser uid=1010 group=testusers home=/shared/testuser createhome=no

- include: config.yml
  when: ansible_hostname == "master"
