- name: create test user group
  group: name={{group}} gid={{groupid}}

- name: create test user
  user: name={{user}} uid={{userid}} group={{group}} home={{nfsdir}}/{{user}} createhome=no

- include: config.yml
  when: ansible_hostname == "master"
