- hosts: master
  roles:
    - nfsmaster
    - testuser
    - munge
    - slurmmaster
    - openmpi
    - singularity

- hosts: c01:c02:c03
  roles:
    - nfsclient
    - testuser
    - munge
    - slurm
    - openmpi
    - singularity
