  - name: install list of packages
    yum: name={{item}} state=installed
    with_items:
      - openssl-devel
      - gcc
      - unzip

  - copy: 
      src: munge-munge-0.5.12.zip
      dest: /tmp/munge-munge-0.5.12.zip

  - script: install_munge.sh
    args:
      creates: /etc/init.d/munge

  - copy:
      src: munge.key
      dest: /etc/munge/munge.key
      owner: munge
      group: munge
      mode: 0400

  - name: start munge service
    service: name=munge state=started enabled=true

        
