- hosts: master

  tasks:

    - name: Install Httpd Package
      yum: name=httpd state=latest
      sudo: yes

    - name: Start Httpd Service 
      service: name=httpd state=started
      sudo: yes

- hosts: client

  tasks:

    - name: Install Vim
      yum: name=emacs state=latest
      sudo: yes
